server:
  servlet:
    context-path: /api
spring:
#  profiles:
#    active: local
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    username:
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        opaque-token:
          instrospect-uri: https://www.googleapis.com/oauth2/v3
          clientId: ${CLIENT_ID}
          clientSecret: ${CLIENT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health

front-end:
  url: ${FRONTEND_URL}
google:
  authorization-code-request-url: https://accounts.google.com/o/oauth2/auth?access_type=offline
