spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
      resourceserver:
        jwt:
          issuerUri: https://accounts.google.com