spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        opaque-token:
          instrospect-uri: https://www.googleapis.com/oauth2/v3
          clientId: ${CLIENT_ID}
          clientSecret: ${CLIENT_SECRET}
front-end:
  url: http://localhost:4200
google:
  authorization-code-request-url: https://accounts.google.com/o/oauth2/auth?access_type=offline