spring:
  security:
    oauth2:
      resourceserver:
        opaque-token:
          instrospect-uri: https://www.googleapis.com
          clientId: ${CLIENT_ID}
          clientSecret: ${CLIENT_SECRET}